/*
Copyright 2025 The KubeVela Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

package workflowsteps

import (
	"github.com/oam-dev/kubevela/pkg/definition/defkit"
)

// GenerateJDBCConnection creates the generate-jdbc-connection workflow step definition.
// This step generates a JDBC connection based on Component of alibaba-rds.
func GenerateJDBCConnection() *defkit.WorkflowStepDefinition {
	return defkit.NewWorkflowStep("generate-jdbc-connection").
		Description("Generate a JDBC connection based on Component of alibaba-rds").
		RawCUE(`import (
	"vela/kube"
	"vela/util"
	"encoding/base64"
)

"generate-jdbc-connection": {
	type: "workflow-step"
	annotations: {
		"category": "Terraform"
	}
	description: "Generate a JDBC connection based on Component of alibaba-rds"
}
template: {
	output: kube.#Read & {
		$params: {
			value: {
				apiVersion: "v1"
				kind:       "Secret"
				metadata: {
					name: parameter.name
					if parameter.namespace != _|_ {
						namespace: parameter.namespace
					}
				}
			}
		}
	}
	dbHost: util.#ConvertString & {$params: bt: base64.Decode(null, output.$returns.value.data["DB_HOST"])}
	dbPort: util.#ConvertString & {$params: bt: base64.Decode(null, output.$returns.value.data["DB_PORT"])}
	dbName: util.#ConvertString & {$params: bt: base64.Decode(null, output.$returns.value.data["DB_NAME"])}
	username: util.#ConvertString & {$params: bt: base64.Decode(null, output.$returns.value.data["DB_USER"])}
	password: util.#ConvertString & {$params: bt: base64.Decode(null, output.$returns.value.data["DB_PASSWORD"])}

	env: [
		{name: "url", value: "jdbc://" + dbHost.$returns.str + ":" + dbPort.$returns.str + "/" + dbName.$returns.str + "?characterEncoding=utf8&useSSL=false"},
		{name: "username", value: username.$returns.str},
		{name: "password", value: password.$returns.str},
	]

	parameter: {
		// +usage=Specify the name of the secret generated by database component
		name: string
		// +usage=Specify the namespace of the secret generated by database component
		namespace?: string
	}
}
`)
}

func init() {
	defkit.Register(GenerateJDBCConnection())
}
