/*
Copyright 2025 The KubeVela Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Package main generates CUE files for all registered trait definitions.
// For each trait, it creates a directory named after the trait containing:
//   - <name>-defkit.cue: generated by defkit's ToCue()
//   - <name>-vela.cue: copied from kubevela/vela-templates/definitions/internal/trait/
//
// Usage: go run ./cmd/traitcue [--output-dir <dir>]
package main

import (
	"flag"
	"fmt"
	"os"
	"path/filepath"

	"github.com/oam-dev/kubevela/pkg/definition/defkit"

	// Import trait package to trigger init() registration
	_ "github.com/oam-dev/vela-go-definitions/traits"
)

func main() {
	outputDir := flag.String("output-dir", "../translations/traits", "output directory for generated trait CUE files")
	velaTraitDir := flag.String("vela-trait-dir", "../kubevela/vela-templates/definitions/internal/trait", "path to kubevela vela-templates trait directory")
	flag.Parse()

	traits := defkit.Traits()
	if len(traits) == 0 {
		fmt.Fprintln(os.Stderr, "no traits registered")
		os.Exit(1)
	}

	fmt.Printf("Found %d registered traits\n", len(traits))

	for _, trait := range traits {
		name := trait.GetName()
		traitDir := filepath.Join(*outputDir, name)

		if err := os.MkdirAll(traitDir, 0o755); err != nil {
			fmt.Fprintf(os.Stderr, "failed to create directory %s: %v\n", traitDir, err)
			os.Exit(1)
		}

		// Write defkit-generated CUE
		defkitCUE := trait.ToCue()
		defkitPath := filepath.Join(traitDir, name+"-defkit.cue")
		if err := os.WriteFile(defkitPath, []byte(defkitCUE), 0o644); err != nil {
			fmt.Fprintf(os.Stderr, "failed to write %s: %v\n", defkitPath, err)
			os.Exit(1)
		}

		// Copy vela CUE template
		velaSrc := filepath.Join(*velaTraitDir, name+".cue")
		velaContent, err := os.ReadFile(velaSrc)
		if err != nil {
			fmt.Fprintf(os.Stderr, "warning: vela CUE not found for %q at %s: %v\n", name, velaSrc, err)
			continue
		}
		velaPath := filepath.Join(traitDir, name+"-vela.cue")
		if err := os.WriteFile(velaPath, velaContent, 0o644); err != nil {
			fmt.Fprintf(os.Stderr, "failed to write %s: %v\n", velaPath, err)
			os.Exit(1)
		}

		fmt.Printf("  %s/\n    %s-defkit.cue\n    %s-vela.cue\n", name, name, name)
	}

	fmt.Printf("\nDone. Output written to %s/\n", *outputDir)
}
